### ISSUE TITLE
Apparently im banned from sage.party.

### ISSUE THREAD

**Issue by FatLardXr41** [sag-enhanced/native-app#2]
According to the native SAGE app im banned. but when i visit sage.party its fine?????

**Comment by FatLardXr41** [comment]
![image](https://github.com/sag-enhanced/native-app/assets/148020755/97238ddb-6189-4465-9bca-acdcbff74f38)

**Comment by Wicctory** [comment]
same issue here

**Comment by Le0Developer** [comment]
Use b3.
The issue is that the webview version on linux is weird and doesn't have some features, so it gets blocked by the WAF.
b3 is using playwright on linux as UI instead.
